### ISSUE TITLE
Uncaught exception in backend/metrics.py

### ISSUE THREAD

**Issue by wllgrnt** [trynmaps/metrics-mvp#547]
If you navigate through to the stop-to-stop view, then select an invalid set of days (e.g. if you choose a date corresponding to a Wednesday but only the "Weekend" button ) then a ValueError gets thrown, which we should probably handle somehow.

![Selection_040](https://user-images.githubusercontent.com/14338351/74395181-85626100-4dc3-11ea-9003-7c7ce5086248.png)

Locally, I get:

```
metrics-flask-dev | An error occurred while resolving field TripIntervalMetrics.tripTimes
metrics-flask-dev | Traceback (most recent call last):
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
metrics-flask-dev |     return executor.execute(resolve_fn, source, info, **args)
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
metrics-flask-dev |     return fn(*args, **kwargs)
metrics-flask-dev |   File "/app/backend/models/schema.py", line 365, in resolve_tripTimes
metrics-flask-dev |     rng = parent["range"]
metrics-flask-dev |   File "/app/backend/models/metrics.py", line 266, in get_trip_times
metrics-flask-dev |     return self._get_trip_times(direction_id, start_stop_id, end_stop_id, rng, self.get_history_data_frame)
metrics-flask-dev |   File "/app/backend/models/metrics.py", line 317, in _get_trip_times
metrics-flask-dev |     return np.concatenate(completed_trips_arr)
metrics-flask-dev | ValueError: need at least one array to concatenate
metrics-flask-dev | Traceback (most recent call last):
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
metrics-flask-dev |     return executor.execute(resolve_fn, source, info, **args)
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
metrics-flask-dev |     return fn(*args, **kwargs)
metrics-flask-dev |   File "/app/backend/models/schema.py", line 365, in resolve_tripTimes
metrics-flask-dev |     rng = parent["range"]
metrics-flask-dev |   File "/app/backend/models/metrics.py", line 266, in get_trip_times
metrics-flask-dev |     return self._get_trip_times(direction_id, start_stop_id, end_stop_id, rng, self.get_history_data_frame)
metrics-flask-dev |   File "/app/backend/models/metrics.py", line 317, in _get_trip_times
metrics-flask-dev |     return np.concatenate(completed_trips_arr)
metrics-flask-dev | graphql.error.located_error.GraphQLLocatedError: need at least one array to concatenate
```

So I'm guessing we need a guard clause in get_trip_times, in backend/models/metrics.py

**Comment by hathix** [comment]
[This guide](https://docs.google.com/document/d/1RpVZsbBHFiPLXbKcmsa4gi68ab-C_yi1Ar3lHshu6i4/edit#) has usability tips for the frontend, in case your solution is going to touch that.
